# -*- coding: utf-8 -*-
import keyboard_config

questions_data = {
    1: ["Кличка питомца?", keyboard_config.keyboard_skip],
    2: ["Порода?", keyboard_config.keyboard_skip],
    3: ["День рождения питомца? (Можно приблизительно)", keyboard_config.keyboard_skip],
    4: ["Пол питомца?", keyboard_config.keyboard_answer_4],
    5: ["Вес питомца?", keyboard_config.keyboard_skip],
    6: ["Есть ли у питомца ветпаспорт?", keyboard_config.keyboard_answer],
    7: ["Делали ли вы прививки своему питомцу?", keyboard_config.keyboard_answer],
    8: ["Есть ли защита от клещей? (Прививки, специальный ошейник и т.д.)", keyboard_config.keyboard_answer],
    9: ["Ваш питомец кастрирован/стерилизован?", keyboard_config.keyboard_answer],
    10: ["Были ли у питомца травмы?", keyboard_config.keyboard_answer],
    11: ["Если да, то какие?", keyboard_config.keyboard_skip],
    12: ["Тянет ли за поводок?", keyboard_config.keyboard_answer_10],
    13: ["Подбирает с земли?", keyboard_config.keyboard_answer_11],
    14: ["Если подберет, можно отобрать?", keyboard_config.keyboard_answer_12],
    15: ["К чему или к кому есть агрессия?", keyboard_config.keyboard_skip],
    16: ["Чего боится ваш питомец?", keyboard_config.keyboard_skip],
    17: ["Можно отпускать на собачьей площадке без поводка?", keyboard_config.keyboard_answer],
    18: ["Можно ли контактировать с другими собаками?", keyboard_config.keyboard_answer],
    19: ["Надо ли мыть лапки после прогулки?", keyboard_config.keyboard_answer],
    20: ["Где вы обычно моете лапки питомца?", keyboard_config.keyboard_skip],
    21: ["Нужно покормить после прогулки?", keyboard_config.keyboard_answer],
    22: ["Если нужно, то чем кормить? Какая порция?", keyboard_config.keyboard_answer_21],
    23: ["Какая длительность выгула комфортна для питомца?\nЦена указана без учёта скидок и дополнительных услуг", keyboard_config.keyboard_answer_21],
    24: ["Когда вы хотите познакомиться с потенциальным выгульщиком?", keyboard_config.keyboard_answer_23],
    25: ["Как нам попасть к питомцу?", keyboard_config.keyboard_answer_24],
    26: ["Во сколько вам будет удобно принять звонок?", keyboard_config.keyboard_answer_29],
    27: ["Ваше имя и фамилия?", keyboard_config.keyboard_skip],
    28: ["Ваш телефон?", keyboard_config.keyboard_skip],
    29: ["Ваш e-mail?", keyboard_config.keyboard_skip],
    30: ["Отлично! Менеджер свяжется с вами в указаное время.", keyboard_config.keyboard_answer_result]
}
